package com.suxton.kunmall.dao;

import com.suxton.kunmall.pojo.Cart;
import com.suxton.kunmall.pojo.CartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    long countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int insert(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int insertSelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    Cart selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int updateByExampleSelective(@Param("row") Cart row, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int updateByExample(@Param("row") Cart row, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int updateByPrimaryKeySelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cart
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    int updateByPrimaryKey(Cart row);
}