package com.suxton.kunmall.dao;

import com.suxton.kunmall.pojo.Comment;
import com.suxton.kunmall.pojo.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int insert(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int insertSelective(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    List<Comment> selectByExampleWithBLOBs(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") Comment row, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Comment row, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByExample(@Param("row") Comment row, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByPrimaryKeySelective(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByPrimaryKey(Comment row);
}