package com.suxton.kunmall.dao;

import com.suxton.kunmall.pojo.Moment;
import com.suxton.kunmall.pojo.MomentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    long countByExample(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int deleteByExample(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int insert(Moment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int insertSelective(Moment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    List<Moment> selectByExampleWithBLOBs(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    List<Moment> selectByExample(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    Moment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") Moment row, @Param("example") MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Moment row, @Param("example") MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByExample(@Param("row") Moment row, @Param("example") MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByPrimaryKeySelective(Moment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Moment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Moment
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    int updateByPrimaryKey(Moment row);
}