package com.suxton.kunmall.dao;

import com.suxton.kunmall.pojo.MomentLike;
import com.suxton.kunmall.pojo.MomentLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomentLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    long countByExample(MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int deleteByExample(MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int insert(MomentLike row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int insertSelective(MomentLike row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    List<MomentLike> selectByExample(MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByExampleSelective(@Param("row") MomentLike row, @Param("example") MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MomentLike
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByExample(@Param("row") MomentLike row, @Param("example") MomentLikeExample example);
}