package com.suxton.kunmall.dao;

import com.suxton.kunmall.pojo.Photo;
import com.suxton.kunmall.pojo.PhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    long countByExample(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int deleteByExample(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int insert(Photo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int insertSelective(Photo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    List<Photo> selectByExampleWithBLOBs(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    List<Photo> selectByExample(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    Photo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByExampleSelective(@Param("row") Photo row, @Param("example") PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Photo row, @Param("example") PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByExample(@Param("row") Photo row, @Param("example") PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByPrimaryKeySelective(Photo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Photo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Photo
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    int updateByPrimaryKey(Photo row);
}