package com.suxton.kunmall.dao;

import com.suxton.kunmall.pojo.Service;
import com.suxton.kunmall.pojo.ServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    long countByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int deleteByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int insert(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int insertSelective(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    List<Service> selectByExampleWithBLOBs(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    List<Service> selectByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    Service selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int updateByExampleSelective(@Param("row") Service row, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Service row, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int updateByExample(@Param("row") Service row, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int updateByPrimaryKeySelective(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Service
     *
     * @mbg.generated Mon Jul 17 11:47:12 CST 2023
     */
    int updateByPrimaryKey(Service row);
}