package com.suxton.kunmall.mapper;

import com.suxton.kunmall.entity.Drive;
import com.suxton.kunmall.entity.DriveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    long countByExample(DriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int deleteByExample(DriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int insert(Drive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int insertSelective(Drive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    List<Drive> selectByExample(DriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    Drive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByExampleSelective(@Param("row") Drive row, @Param("example") DriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByExample(@Param("row") Drive row, @Param("example") DriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByPrimaryKeySelective(Drive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Drive
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByPrimaryKey(Drive row);
}