package com.suxton.kunmall.mapper;

import com.suxton.kunmall.entity.Orders;
import com.suxton.kunmall.entity.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int insert(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int insertSelective(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByExampleSelective(@Param("row") Orders row, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByExample(@Param("row") Orders row, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByPrimaryKeySelective(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    int updateByPrimaryKey(Orders row);
}