package com.suxton.kunmall.pojo;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.userID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.id
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.CPUID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    private Integer cpuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.GPUID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    private Integer gpuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.DriveID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    private Integer driveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Cart.MemoryID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    private Integer memoryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.userID
     *
     * @return the value of Cart.userID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.userID
     *
     * @param userid the value for Cart.userID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.id
     *
     * @return the value of Cart.id
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.id
     *
     * @param id the value for Cart.id
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.CPUID
     *
     * @return the value of Cart.CPUID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public Integer getCpuid() {
        return cpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.CPUID
     *
     * @param cpuid the value for Cart.CPUID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public void setCpuid(Integer cpuid) {
        this.cpuid = cpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.GPUID
     *
     * @return the value of Cart.GPUID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public Integer getGpuid() {
        return gpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.GPUID
     *
     * @param gpuid the value for Cart.GPUID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public void setGpuid(Integer gpuid) {
        this.gpuid = gpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.DriveID
     *
     * @return the value of Cart.DriveID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public Integer getDriveid() {
        return driveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.DriveID
     *
     * @param driveid the value for Cart.DriveID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public void setDriveid(Integer driveid) {
        this.driveid = driveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Cart.MemoryID
     *
     * @return the value of Cart.MemoryID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public Integer getMemoryid() {
        return memoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Cart.MemoryID
     *
     * @param memoryid the value for Cart.MemoryID
     *
     * @mbg.generated Sun Jul 16 01:09:12 CST 2023
     */
    public void setMemoryid(Integer memoryid) {
        this.memoryid = memoryid;
    }
}