package com.suxton.kunmall.pojo;

public class MomentLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MomentLike.user_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MomentLike.moment_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer momentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MomentLike.user_id
     *
     * @return the value of MomentLike.user_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MomentLike.user_id
     *
     * @param userId the value for MomentLike.user_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MomentLike.moment_id
     *
     * @return the value of MomentLike.moment_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getMomentId() {
        return momentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MomentLike.moment_id
     *
     * @param momentId the value for MomentLike.moment_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setMomentId(Integer momentId) {
        this.momentId = momentId;
    }
}