package com.suxton.kunmall.pojo;

public class Moment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.user_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.user_name
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.like_num
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.comment_num
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.time_posted
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Long timePosted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Moment.content
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.id
     *
     * @return the value of Moment.id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.id
     *
     * @param id the value for Moment.id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.user_id
     *
     * @return the value of Moment.user_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.user_id
     *
     * @param userId the value for Moment.user_id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.user_name
     *
     * @return the value of Moment.user_name
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.user_name
     *
     * @param userName the value for Moment.user_name
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.like_num
     *
     * @return the value of Moment.like_num
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.like_num
     *
     * @param likeNum the value for Moment.like_num
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.comment_num
     *
     * @return the value of Moment.comment_num
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.comment_num
     *
     * @param commentNum the value for Moment.comment_num
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.time_posted
     *
     * @return the value of Moment.time_posted
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Long getTimePosted() {
        return timePosted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.time_posted
     *
     * @param timePosted the value for Moment.time_posted
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setTimePosted(Long timePosted) {
        this.timePosted = timePosted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Moment.content
     *
     * @return the value of Moment.content
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Moment.content
     *
     * @param content the value for Moment.content
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}