package com.suxton.kunmall.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCpuidIsNull() {
            addCriterion("CPUID is null");
            return (Criteria) this;
        }

        public Criteria andCpuidIsNotNull() {
            addCriterion("CPUID is not null");
            return (Criteria) this;
        }

        public Criteria andCpuidEqualTo(Integer value) {
            addCriterion("CPUID =", value, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidNotEqualTo(Integer value) {
            addCriterion("CPUID <>", value, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidGreaterThan(Integer value) {
            addCriterion("CPUID >", value, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CPUID >=", value, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidLessThan(Integer value) {
            addCriterion("CPUID <", value, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidLessThanOrEqualTo(Integer value) {
            addCriterion("CPUID <=", value, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidIn(List<Integer> values) {
            addCriterion("CPUID in", values, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidNotIn(List<Integer> values) {
            addCriterion("CPUID not in", values, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidBetween(Integer value1, Integer value2) {
            addCriterion("CPUID between", value1, value2, "cpuid");
            return (Criteria) this;
        }

        public Criteria andCpuidNotBetween(Integer value1, Integer value2) {
            addCriterion("CPUID not between", value1, value2, "cpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidIsNull() {
            addCriterion("GPUID is null");
            return (Criteria) this;
        }

        public Criteria andGpuidIsNotNull() {
            addCriterion("GPUID is not null");
            return (Criteria) this;
        }

        public Criteria andGpuidEqualTo(Integer value) {
            addCriterion("GPUID =", value, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidNotEqualTo(Integer value) {
            addCriterion("GPUID <>", value, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidGreaterThan(Integer value) {
            addCriterion("GPUID >", value, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("GPUID >=", value, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidLessThan(Integer value) {
            addCriterion("GPUID <", value, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidLessThanOrEqualTo(Integer value) {
            addCriterion("GPUID <=", value, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidIn(List<Integer> values) {
            addCriterion("GPUID in", values, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidNotIn(List<Integer> values) {
            addCriterion("GPUID not in", values, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidBetween(Integer value1, Integer value2) {
            addCriterion("GPUID between", value1, value2, "gpuid");
            return (Criteria) this;
        }

        public Criteria andGpuidNotBetween(Integer value1, Integer value2) {
            addCriterion("GPUID not between", value1, value2, "gpuid");
            return (Criteria) this;
        }

        public Criteria andDriveidIsNull() {
            addCriterion("DriveID is null");
            return (Criteria) this;
        }

        public Criteria andDriveidIsNotNull() {
            addCriterion("DriveID is not null");
            return (Criteria) this;
        }

        public Criteria andDriveidEqualTo(Integer value) {
            addCriterion("DriveID =", value, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidNotEqualTo(Integer value) {
            addCriterion("DriveID <>", value, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidGreaterThan(Integer value) {
            addCriterion("DriveID >", value, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidGreaterThanOrEqualTo(Integer value) {
            addCriterion("DriveID >=", value, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidLessThan(Integer value) {
            addCriterion("DriveID <", value, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidLessThanOrEqualTo(Integer value) {
            addCriterion("DriveID <=", value, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidIn(List<Integer> values) {
            addCriterion("DriveID in", values, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidNotIn(List<Integer> values) {
            addCriterion("DriveID not in", values, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidBetween(Integer value1, Integer value2) {
            addCriterion("DriveID between", value1, value2, "driveid");
            return (Criteria) this;
        }

        public Criteria andDriveidNotBetween(Integer value1, Integer value2) {
            addCriterion("DriveID not between", value1, value2, "driveid");
            return (Criteria) this;
        }

        public Criteria andMemoryidIsNull() {
            addCriterion("MemoryID is null");
            return (Criteria) this;
        }

        public Criteria andMemoryidIsNotNull() {
            addCriterion("MemoryID is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryidEqualTo(Integer value) {
            addCriterion("MemoryID =", value, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidNotEqualTo(Integer value) {
            addCriterion("MemoryID <>", value, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidGreaterThan(Integer value) {
            addCriterion("MemoryID >", value, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("MemoryID >=", value, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidLessThan(Integer value) {
            addCriterion("MemoryID <", value, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidLessThanOrEqualTo(Integer value) {
            addCriterion("MemoryID <=", value, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidIn(List<Integer> values) {
            addCriterion("MemoryID in", values, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidNotIn(List<Integer> values) {
            addCriterion("MemoryID not in", values, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidBetween(Integer value1, Integer value2) {
            addCriterion("MemoryID between", value1, value2, "memoryid");
            return (Criteria) this;
        }

        public Criteria andMemoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("MemoryID not between", value1, value2, "memoryid");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNull() {
            addCriterion("orderTime is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNotNull() {
            addCriterion("orderTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeEqualTo(Date value) {
            addCriterion("orderTime =", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotEqualTo(Date value) {
            addCriterion("orderTime <>", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThan(Date value) {
            addCriterion("orderTime >", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("orderTime >=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThan(Date value) {
            addCriterion("orderTime <", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThanOrEqualTo(Date value) {
            addCriterion("orderTime <=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIn(List<Date> values) {
            addCriterion("orderTime in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotIn(List<Date> values) {
            addCriterion("orderTime not in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeBetween(Date value1, Date value2) {
            addCriterion("orderTime between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotBetween(Date value1, Date value2) {
            addCriterion("orderTime not between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Orders
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 14 19:37:29 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Orders
     *
     * @mbg.generated Fri Jul 14 19:37:29 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}