package com.suxton.kunmall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.id
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.userID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.CPUID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Integer cpuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.GPUID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Integer gpuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.DriveID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Integer driveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.MemoryID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Integer memoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.address
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.money
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.orderTime
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.status
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.comment
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.id
     *
     * @return the value of Orders.id
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.id
     *
     * @param id the value for Orders.id
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.userID
     *
     * @return the value of Orders.userID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.userID
     *
     * @param userid the value for Orders.userID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.CPUID
     *
     * @return the value of Orders.CPUID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Integer getCpuid() {
        return cpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.CPUID
     *
     * @param cpuid the value for Orders.CPUID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setCpuid(Integer cpuid) {
        this.cpuid = cpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.GPUID
     *
     * @return the value of Orders.GPUID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Integer getGpuid() {
        return gpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.GPUID
     *
     * @param gpuid the value for Orders.GPUID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setGpuid(Integer gpuid) {
        this.gpuid = gpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.DriveID
     *
     * @return the value of Orders.DriveID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Integer getDriveid() {
        return driveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.DriveID
     *
     * @param driveid the value for Orders.DriveID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setDriveid(Integer driveid) {
        this.driveid = driveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.MemoryID
     *
     * @return the value of Orders.MemoryID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Integer getMemoryid() {
        return memoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.MemoryID
     *
     * @param memoryid the value for Orders.MemoryID
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setMemoryid(Integer memoryid) {
        this.memoryid = memoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.address
     *
     * @return the value of Orders.address
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.address
     *
     * @param address the value for Orders.address
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.money
     *
     * @return the value of Orders.money
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.money
     *
     * @param money the value for Orders.money
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.orderTime
     *
     * @return the value of Orders.orderTime
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.orderTime
     *
     * @param ordertime the value for Orders.orderTime
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.status
     *
     * @return the value of Orders.status
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.status
     *
     * @param status the value for Orders.status
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.comment
     *
     * @return the value of Orders.comment
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.comment
     *
     * @param comment the value for Orders.comment
     *
     * @mbg.generated Fri Jul 14 14:21:49 CST 2023
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}