package com.suxton.kunmall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.userID
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.CPUName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String cpuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.GPUName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String gpuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.DriveName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String drivename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.MemoryName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String memoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.address
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.money
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.orderTime
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.status
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Orders.comment
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.id
     *
     * @return the value of Orders.id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.id
     *
     * @param id the value for Orders.id
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.userID
     *
     * @return the value of Orders.userID
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.userID
     *
     * @param userid the value for Orders.userID
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.CPUName
     *
     * @return the value of Orders.CPUName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getCpuname() {
        return cpuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.CPUName
     *
     * @param cpuname the value for Orders.CPUName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setCpuname(String cpuname) {
        this.cpuname = cpuname == null ? null : cpuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.GPUName
     *
     * @return the value of Orders.GPUName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getGpuname() {
        return gpuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.GPUName
     *
     * @param gpuname the value for Orders.GPUName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setGpuname(String gpuname) {
        this.gpuname = gpuname == null ? null : gpuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.DriveName
     *
     * @return the value of Orders.DriveName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getDrivename() {
        return drivename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.DriveName
     *
     * @param drivename the value for Orders.DriveName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setDrivename(String drivename) {
        this.drivename = drivename == null ? null : drivename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.MemoryName
     *
     * @return the value of Orders.MemoryName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getMemoryname() {
        return memoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.MemoryName
     *
     * @param memoryname the value for Orders.MemoryName
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setMemoryname(String memoryname) {
        this.memoryname = memoryname == null ? null : memoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.address
     *
     * @return the value of Orders.address
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.address
     *
     * @param address the value for Orders.address
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.money
     *
     * @return the value of Orders.money
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.money
     *
     * @param money the value for Orders.money
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.orderTime
     *
     * @return the value of Orders.orderTime
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.orderTime
     *
     * @param ordertime the value for Orders.orderTime
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.status
     *
     * @return the value of Orders.status
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.status
     *
     * @param status the value for Orders.status
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Orders.comment
     *
     * @return the value of Orders.comment
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Orders.comment
     *
     * @param comment the value for Orders.comment
     *
     * @mbg.generated Thu Jan 25 18:43:37 CST 2024
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}