package com.suxton.kunmall.pojo;

public class Recommends {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Recommends.id
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Recommends.CPUID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    private Integer cpuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Recommends.GPUID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    private Integer gpuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Recommends.DriveID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    private Integer driveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Recommends.MemoryID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    private Integer memoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Recommends.comment
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Recommends.id
     *
     * @return the value of Recommends.id
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Recommends.id
     *
     * @param id the value for Recommends.id
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Recommends.CPUID
     *
     * @return the value of Recommends.CPUID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public Integer getCpuid() {
        return cpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Recommends.CPUID
     *
     * @param cpuid the value for Recommends.CPUID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public void setCpuid(Integer cpuid) {
        this.cpuid = cpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Recommends.GPUID
     *
     * @return the value of Recommends.GPUID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public Integer getGpuid() {
        return gpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Recommends.GPUID
     *
     * @param gpuid the value for Recommends.GPUID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public void setGpuid(Integer gpuid) {
        this.gpuid = gpuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Recommends.DriveID
     *
     * @return the value of Recommends.DriveID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public Integer getDriveid() {
        return driveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Recommends.DriveID
     *
     * @param driveid the value for Recommends.DriveID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public void setDriveid(Integer driveid) {
        this.driveid = driveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Recommends.MemoryID
     *
     * @return the value of Recommends.MemoryID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public Integer getMemoryid() {
        return memoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Recommends.MemoryID
     *
     * @param memoryid the value for Recommends.MemoryID
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public void setMemoryid(Integer memoryid) {
        this.memoryid = memoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Recommends.comment
     *
     * @return the value of Recommends.comment
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Recommends.comment
     *
     * @param comment the value for Recommends.comment
     *
     * @mbg.generated Sun Jul 16 13:01:55 CST 2023
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}