package com.suxton.kunmall.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.id
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.userName
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.isAdmin
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    private Boolean isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.passwd
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.id
     *
     * @return the value of Users.id
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.id
     *
     * @param id the value for Users.id
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.userName
     *
     * @return the value of Users.userName
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.userName
     *
     * @param username the value for Users.userName
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.isAdmin
     *
     * @return the value of Users.isAdmin
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public Boolean getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.isAdmin
     *
     * @param isadmin the value for Users.isAdmin
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public void setIsadmin(Boolean isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.passwd
     *
     * @return the value of Users.passwd
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.passwd
     *
     * @param passwd the value for Users.passwd
     *
     * @mbg.generated Thu Jan 25 16:04:20 CST 2024
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }
}